### ISSUE TITLE
Getting errors running script on WIndows 11

### ISSUE THREAD

**Issue by tichaonax** [springcomp/my-box#1]
Thank you for putting together this script to make it simpler to install
I upgraded from windows pro 10 to latest windows 11 insider build and I am getting the following errors:

iex "& { $(irm 'https://raw.githubusercontent.com/springcomp/my-box/main/bootstrap/powershell.ps1') }"

```

Install-Profile: C:\Users\ticha\AppData\Local\Temp\pwsh-core.ps1:93
Line |
  93 |      Install-Profile "psreadline" -Load
     |      ~~~~~~~~~~~~~~~
     | The term 'Install-Profile' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Update-PoshTheme: C:\Users\ticha\AppData\Local\Temp\pwsh-core.ps1:95
Line |
  95 |      Update-PoshTheme
     |      ~~~~~~~~~~~~~~~~
     | The term 'Update-PoshTheme' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Upgrade-OhMyPosh: C:\Users\ticha\AppData\Local\Temp\pwsh-core.ps1:96
Line |
  96 |      Upgrade-OhMyPosh
     |      ~~~~~~~~~~~~~~~~
     | The term 'Upgrade-OhMyPosh' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Upgrade-TerminalIcons: C:\Users\ticha\AppData\Local\Temp\pwsh-core.ps1:97
Line |
  97 |      Upgrade-TerminalIcons
     |      ~~~~~~~~~~~~~~~~~~~~~
     | The term 'Upgrade-TerminalIcons' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

```

**Comment by springcomp** [comment]
@tichaonax thanks for the feedback.
This issue is now fixed.

Please, try again 👍

**Comment by tichaonax** [comment]
I ran it again, it went past the previous error: Below is the new error message:
```
VERBOSE: Latest PowerShell Daily already installed.
GET https://raw.githubusercontent.com/springcomp/powershell_profile.ps1/master/Microsoft.PowerShell_profile.ps1 HTTP/1.1
C:\Users\ticha\Documents\PowerShell\Microsoft.PowerShell_profile.ps1 updated.
https://raw.githubusercontent.com/springcomp/powershell_profile.ps1/master/Microsoft.PowerShell_oh-my-posh-profile.ps1
C:\Users\ticha\Documents\PowerShell\Microsoft.PowerShell_oh-my-posh-profile.ps1
C:\Users\ticha\Documents\PowerShell\Microsoft.PowerShell_oh-my-posh-profile.ps1 updated.
Loading oh-my-posh profile.
https://raw.githubusercontent.com/springcomp/powershell_profile.ps1/master/Microsoft.PowerShell_psreadline-profile.ps1
C:\Users\ticha\Documents\PowerShell\Microsoft.PowerShell_psreadline-profile.ps1
C:\Users\ticha\Documents\PowerShell\Microsoft.PowerShell_psreadline-profile.ps1 updated.
Loading psreadline profile.
Update-Module: C:\Users\ticha\AppData\Local\Temp\PowerShell_profiles\Microsoft.PowerShell_oh-my-posh-profile.ps1:13
Line |
  13 |  … le "oh-my-posh" -ListAvailable) { Update-Module "oh-my-posh" -Force }
     |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Module 'oh-my-posh' was not installed by using Install-Module, so it cannot be updated.

Update-Module: C:\Users\ticha\AppData\Local\Temp\PowerShell_profiles\Microsoft.PowerShell_oh-my-posh-profile.ps1:20
Line |
  20 |  … erminal-Icons -ListAvailable) { Update-Module Terminal-Icons -Force }
     |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Module 'Terminal-Icons' was not installed by using Install-Module, so it cannot be updated.
```

**Comment by tichaonax** [comment]
Could this be due to manual install attempts I made. Could the script be made to handle such scenarios also that would be great.

**Comment by springcomp** [comment]
Oh I see what’s happening.

Yes, indeed, these are due to manual install attempts.
For some reason, the module handling of PowerShell is broken in that you cannot easily specify where to install modules.
It appears you already have PowerShell Core 7.1.x installed and you manually installed Oh-My-Posh and Terminal-Icons.

So I think you got past the installation and you have every dependency set up.

You are right, this script is not re-entrant and cannot be run again.
I raised #2 to track this issue.

How are you liking the extensible profile experience from https://github.com/springcomp/powershell_profile.ps1 ?

Thanks for your feedback.

**Comment by tichaonax** [comment]
I definitely like what you put together. My problem is that the icons are not showing and I am not able to fix it. I thought if your script went through successfully the problem would go away.

![image](https://user-images.githubusercontent.com/1031407/137618749-0c7c26e3-e06e-4f75-857b-9026145632a6.png)

**Comment by springcomp** [comment]
I see this is Windows Terminal.
Please go into the settings, in the Appearance tab you will be able to select the appropriate font for your profiles : `CaskaydiaCove Nerd Font Mono` installed using my script.

That's this last operation that my script does not cover  😉.

**Comment by tichaonax** [comment]
> I see this is Windows Terminal. Please go into the settings, in the Appearance tab you will be able to select the appropriate font for your profiles : `CaskaydiaCove Nerd Font Mono` installed using my script.
> 
> That's this last operation that my script does not cover 😉.

That is what I was hoping but I do not see the font Tab. I am using Windows 11.

![image](https://user-images.githubusercontent.com/1031407/137642122-85935225-5046-4e9b-88fe-bcbe19e72626.png)

**Comment by tichaonax** [comment]
That worked thanks and keep up the good work!

**Comment by tichaonax** [comment]
What do I need to do to extend the same functionality to other command windows like ubuntu or git-bash
