### ISSUE TITLE
Something missing

### ISSUE THREAD

**Issue by sturlath** [springcomp/my-box#3]
I just ran your script and I´m not getting the arrows (just []) . Do you know what I need to do to get them?
![image](https://user-images.githubusercontent.com/2386572/140904871-17950228-d323-47a2-9d62-45d1720cc62a.png)

**Comment by springcomp** [comment]
Yes, the script installed one of many variations of Nerd Fonts.
Please, open the settings from Windows Terminal, and select the Appearance Tab, then you will find the Font selection parameter. Please, select the "Caskdaydia Cove Nerd Font Mono" font to have all the missing glyphs.

You could any other Nerd font of your choosing but this one is installed automatically by my script.

**Comment by sturlath** [comment]
Awesome it worked! Thanks.
