### ISSUE TITLE
Scripts installed in different directory

### ISSUE THREAD

**Issue by ash-grennan** [springcomp/my-box#4]
Across my machines, the profiles have installed in:

 `C:\Users\MyUser\Documents\PowerShell` 

and not 

`C:\Users\MyUser\Documents\WindowsPowerShell`

My `$PROFILE` is `C:\Users\MyUser\Documents\WindowsPowerShell\ which hasn't been changed, curious if this is something specific to my machines or has been experienced by other people? 

Happy to submit a PR to check the additional dir if this is known.

**Comment by springcomp** [comment]
Hi @ash-grennan  thank you for the feedback.

Indeed, you may have two (or more) different versions of PowerShell in your machine.
- PowerShell Core (pwsh 7.x) installs its profiles in `$Env:USERPROFILE\PowerShell` as you have found out.
- Windows PowerShell (5.x) installs its profiles in `$Env:USERPROFILE\WindowsPowerShell`.

You can have both side by side without any problems.

Do you have any issue at all?

**Comment by ash-grennan** [comment]
Appreciate the response, that makes a whole lot of sense, no issue merely curious. Hopefully, this helps someone else out in the future 👍
