### ISSUE TITLE
How do I resolve this?

### ISSUE THREAD

**Issue by darlove** [springcomp/my-box#5]
Hi there. I've got this error when trying to install... How can I resolve this? Thanks.

![image](https://user-images.githubusercontent.com/16683408/182475268-6ba6e39d-2953-4e4a-9d9f-be55724fe720.png)

**Comment by springcomp** [comment]
Oh that's right sorry.
There must have been a bug while running the script.
Please run [this command](https://github.com/springcomp/my-box/blob/e3a2431e448fbf7acad2fe6969a448d00bbedf11/bootstrap/pwsh-core.ps1#L87) which is the new supported way to install oh-my-posh.

Will update my scripts accordingly.
