### ISSUE TITLE
Can not install with the command

### ISSUE THREAD

**Issue by paulkuo123** [springcomp/my-box#6]
Hi:
Thanks for sharing the awesome repo, but I get these errors below. 
How do I solve it?

![image](https://user-images.githubusercontent.com/63280796/191296831-a75de543-6473-4820-9d0c-be4221274cc4.png)

**Comment by springcomp** [comment]
Thanks for reporting.

Oh-My-POSH recently deprecated its Powershell Module as the primary means of setup.
We need to install and setup Oh-My-POSH separately first.

My scripts are not completely up to date at the moment.

In the meantime, please, use the [following command](https://github.com/springcomp/my-box/blob/e3a2431e448fbf7acad2fe6969a448d00bbedf11/bootstrap/pwsh-core.ps1#L83-L88):

```pwsh
. winget install JanDeDobbeleer.OhMyPosh -s winget
```

This requires [WinGet](https://learn.microsoft.com/en-us/windows/package-manager/).
