### ISSUE TITLE
'Upgrade-OhMyPosh' is not recognized

### ISSUE THREAD

**Issue by Ciezo** [springcomp/my-box#8]
I was trying to install this, but then this happened. 

![image](https://github.com/springcomp/my-box/assets/74012129/38ed4926-fc04-48f8-9165-33834b13ee24)

But oh-my-posh command is working.  
![image](https://github.com/springcomp/my-box/assets/74012129/2df20780-63da-4c1f-926d-b6507cef0254)

Please. help

**Comment by Ciezo** [comment]
I have the updated PowerShell Core 7. But it seems your script won't run. Please, help how to fix this. I am running on Windows 11.

**Comment by springcomp** [comment]
Thanks for the feedback.

I have added the missing function.
Please, upgrade to the latest commit.
